# Generated by Django 5.2.7 on 2025-11-04 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='medicine',
        ),
        migrations.AddField(
            model_name='sale',
            name='inventory_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.inventoryitem'),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
