# Generated by Django 5.2.7 on 2025-11-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_inventoryitem_remove_sale_medicine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='buying_price',
        ),
    ]
